import { severityForScore } from "@/scoring/calculator";
import type { GeminiBand, GeminiView } from "@/report/presenters/types";

/**
 * ScoreHero evidence for the landing page (LND-7, design sprint 8 §A6 + A3.2).
 *
 * The landing ScoreHero MUST show a REAL GEO Score produced by the engine
 * (`runAudit`) against candidate URLs - never an invented number. The real
 * evidence is generated by the verification script (A3.1):
 *
 *   pnpm verify:scorehero
 *
 * which audits `scripts/scorehero-verify.test.ts` CANDIDATE_URLS and prints
 * score + band per URL. The best REAL result is copied below as a `GeminiView`
 * (the exact shape `toGeminiViewModel` produces), with its provenance.
 *
 * A3.2 (sprint 14, 2026-09-02): evidence regenerated with the REAL script and
 * engine v3.1.0 (calibration sprint 14). Best real candidate: relevy.app -
 * GEO Score 62 (fair). The dogfooding target (A3.2) now audits well because
 * the live deploy runs the calibrated engine; the batch average was 42.4
 * (gate 40-60) and moz.com measured 57. Category scores below are the REAL
 * `toGeminiViewModel` output of that run, copied verbatim (crawler 95,
 * citability 54.5, E-E-A-T 46, schema 72, platform 70). Weights are the v3.1.0
 * distribution (RGS-1): crawler 15, citability 24, content 23, schema 12,
 * platform 14, brand 12.
 *
 * A3.3 (sprint 21, 2026-09-07): re-pinned after the citability i18n fix.
 * Best real candidate: relevy.app - GEO Score 71 (good). The engine now
 * recognizes Spanish definition/copula/first-person patterns, raising
 * citability 54.5 → 73.9 (see sprint-21-citability-i18n). Category scores
 * below are the REAL `toGeminiViewModel` output of the 2026-09-07 run,
 * copied verbatim (crawler 95, citability 73.9, E-E-A-T 73, schema 93,
 * platform 84). Weights are the v3.1.0 distribution (RGS-1).
 *
 * Brand row honesty (APT-11/RAO-12): on 2026-09-07 the brand probe ran
 * successfully and measured 0 (no Wikipedia/Wikidata presence) - a REAL 0,
 * not a rate-limit null. The row renders 0 with weight 12% and the composite
 * includes the penalty (RGS-11): 71 stays the real v3.1 score.
 */
const VERIFIED_TOTAL_SCORE = 71;
const VERIFIED_DOMAIN = "relevy.app";
const VERIFIED_DATE = "2026-09-07";

export const SCOREHERO_EVIDENCE: GeminiView = {
  totalScore: VERIFIED_TOTAL_SCORE,
  // Band derived from the REAL thresholds (80/65/50/30) - never hand-written,
  // so the chip can not claim a band the score does not deserve.
  band: severityForScore(VERIFIED_TOTAL_SCORE).toLowerCase() as GeminiBand,
  domain: VERIFIED_DOMAIN,
  title: VERIFIED_DOMAIN,
  summary: `${VERIFIED_DOMAIN} - GEO Score ${VERIFIED_TOTAL_SCORE} (${severityForScore(
    VERIFIED_TOTAL_SCORE,
  ).toLowerCase()}) en ~1s`,
  durationSeconds: 1,
  // Real audit date of the verified run (A3.2) - no longer null.
  auditDate: VERIFIED_DATE,
  // Real categoryScores from `pnpm verify:scorehero` (2026-09-02) - the exact
  // `toGeminiViewModel` output for relevy.app, copied verbatim. Six rows with
  // the v3.1 weights; brand is honestly null ("No medido", APT-11) because the
  // probe hit Wikipedia's rate limit (BRA-7/RAO-12) - the composite rebalances
  // (RGS-9).
  categoryScores: [
    {
      id: "crawler",
      name: "Acceso de bots",
      score: 95,
      maxScore: 100,
      weight: "15%",
      status: "excellent",
      keyMetric: null,
      description: "Acceso de los crawlers de IA al sitio.",
    },
    {
      id: "citability",
      name: "Citabilidad",
      score: 73.9,
      maxScore: 100,
      weight: "24%",
      status: "good",
      keyMetric: null,
      description: "Probabilidad de que los asistentes citen los pasajes.",
    },
    {
      id: "content",
      name: "E-E-A-T",
      score: 73,
      maxScore: 100,
      weight: "23%",
      status: "good",
      keyMetric: null,
      description: "Calidad del contenido según E-E-A-T.",
    },
    {
      id: "schema",
      name: "Datos estructurados",
      score: 93,
      maxScore: 100,
      weight: "12%",
      status: "excellent",
      keyMetric: null,
      description: "Marcado de datos estructurados.",
    },
    {
      id: "platform",
      name: "Plataforma",
      score: 84,
      maxScore: 100,
      weight: "14%",
      status: "excellent",
      keyMetric: null,
      description: "Preparación de la plataforma para IA.",
    },
    {
      id: "brand",
      name: "Autoridad de marca",
      // APT-11: REAL measured 0 (2026-09-07) - the probe ran successfully and
      // found no Wikipedia/Wikidata presence. A measured 0 is an honest
      // 12%-weighted penalty (RGS-11), distinct from a rate-limit null.
      score: 0,
      maxScore: 100,
      weight: "12%",
      status: null,
      keyMetric: null,
      description: "Presencia externa de la marca en fuentes que citan las IA.",
    },
  ],
  // The landing renders only the headline + categoryScores (page.tsx gates the
  // breakdown on categoryScores.length > 0). Findings/platforms are not
  // displayed by the landing ScoreHero, so they stay empty here - the evidence
  // contract is satisfied without fabricating rows that the UI does not show.
  findings: [],
  platforms: [],
  shareToken: null,
};
